substitutions:
  # Infra
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _DEPLOY_REGION: us-central1
  _AR_REPO: quark
  _SERVICE_NAME: quark-web
  _RUNTIME_SA: quark-sa
  _IMAGE: ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}
  _CONCURRENCY: "15"
  _LABEL_APP: quark
  _LABEL_ENV: production
  _LABEL_OWNER: lucas

steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${COMMIT_SHA}
      - -t
      - ${_IMAGE}:latest
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}:${COMMIT_SHA}
      - --region=${_DEPLOY_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --cpu=1
      - --timeout=300
      - --min-instances=0
      - --max-instances=5
      - --cpu-boost
      - --concurrency=${_CONCURRENCY}
      - --revision-suffix=${SHORT_SHA}
      - --labels=app=${_LABEL_APP},env=${_LABEL_ENV},owner=${_LABEL_OWNER}
      - --execution-environment=gen2
      - --service-account=${_RUNTIME_SA}@${PROJECT_ID}.iam.gserviceaccount.com

images:
  - ${_IMAGE}:${COMMIT_SHA}
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/${PROJECT_ID}/serviceAccounts/cloud-build-sa@${PROJECT_ID}.iam.gserviceaccount.com
